name: Security and Docker Scan

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Bandit
      run: pip install bandit

    - name: Run Bandit
      run: bandit -r . -o bandit_report.txt

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report
        path: bandit_report.txt

  build_and_scan_docker:
    runs-on: ubuntu-latest
    needs: security_scan

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: |
        docker build -t my-app:latest .

    - name: Install Trivy
      run: |
        sudo apt-get install wget
        wget https://github.com/aquasecurity/trivy/releases/download/v0.35.0/trivy_0.35.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.35.0_Linux-64bit.deb

    - name: Scan Docker Image with Trivy
      run: |
        trivy image -f json -o trivy_report.json my-app:latest

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v3
      with:
        name: trivy-report
        path: trivy_report.json
